### ISSUE TITLE
[🐛 BUG]: Worker panic

### ISSUE THREAD

**Issue by tarampampam** [roadrunner-server/roadrunner#1006]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

During `wrk` test on [tarampampam/laravel-roadrunner-in-docker](https://github.com/tarampampam/laravel-roadrunner-in-docker) template, a panic occurred.

### Version

`2.4.2` - all seems ok
but since `2.5.3 .. 2.7.7` everything goes to hell :D

### Relevant log output

```shell
{"level":"debug","ts":1644566390.9000742,"logger":"server","msg":"worker process exited","reason":"exit status 1; process_wait: exit status 1","reasonCauses":[{"error":"exit status 1"},{"error":"process_wait: exit status 1"}]}
{"level":"debug","ts":1644566396.4822319,"logger":"http","msg":"200 GET http://127.0.0.1:8080/","remote":"192.168.128.1","elapsed":"1.533169837s"}
{"level":"debug","ts":1644566396.4829435,"logger":"static","msg":"possible path to dir provided"}
{"level":"error","ts":1644566396.5586545,"logger":"server","msg":"sync_worker_exec_worker_with_timeout: Network:\n\tsync_worker_exec_payload:\n\tgoridge_frame_receive: CRC verification failed"}
{"level":"error","ts":1644566396.5625384,"logger":"server","msg":"sync_worker_exec_worker_with_timeout: Network:\n\tsync_worker_exec_payload:\n\tgoridge_frame_receive: read unix /var/run/rr/rr-relay.sock->@: read: connection reset by peer"}
{"level":"debug","ts":1644566396.5644958,"logger":"server","msg":"worker process exited","reason":"signal: killed; process_wait: signal: killed","reasonCauses":[{"error":"signal: killed"},{"error":"process_wait: signal: killed"}]}
panic: runtime error: slice bounds out of range [808598050:17915]

goroutine 27217 [running]:
github.com/spiral/roadrunner/v2/worker.(*SyncWorkerImpl).execPayload(0xc0020b5aa0, 0xc001ec40f0)
  github.com/spiral/roadrunner/v2@v2.5.0/worker/sync_worker.go:212 +0xbe5
github.com/spiral/roadrunner/v2/worker.(*SyncWorkerImpl).ExecWithTTL.func1()
  github.com/spiral/roadrunner/v2@v2.5.0/worker/sync_worker.go:105 +0x31a
created by github.com/spiral/roadrunner/v2/worker.(*SyncWorkerImpl).ExecWithTTL
  github.com/spiral/roadrunner/v2@v2.5.0/worker/sync_worker.go:86 +0xd8
```

**Comment by tarampampam** [comment]
@rustatian thanks! 🤝
