### ISSUE TITLE
[🐛 BUG]: segmentation violation when using TLS

### ISSUE THREAD

**Issue by seregazhuk** [roadrunner-server/roadrunner#1278]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Trying to run Temporal worker with mtls support. Have generated certs and using the following config:
```yaml
temporal:
    address: "localhost:7233"
    activities:
        num_workers: 1
    tls:
        key: certs/client.key
        cert: certs/client.pem
```

When running RR receive the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1063c93b8]
```

### Version (rr --version)

2.11.1

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1063c93b8]

goroutine 1 [running]:
github.com/temporalio/roadrunner-temporal.(*Plugin).Serve(0x14000175a40)
	github.com/temporalio/roadrunner-temporal@v1.5.4/plugin.go:154 +0x2f8
reflect.Value.call({0x14000706d80?, 0x1400000e160?, 0x13?}, {0x1063d91be, 0x4}, {0x14000bbf070, 0x1, 0x0?})
	reflect/value.go:584 +0x688
reflect.Value.Call({0x14000706d80?, 0x1400000e160?, 0x5?}, {0x14000bbf070?, 0x1?, 0x1?})
	reflect/value.go:368 +0x90
github.com/roadrunner-server/endure/pkg/container.(*Endure).callServeFn(0x140007fc380, 0x14000694bb0, {0x14000bbf070, 0x1, 0x1})
	github.com/roadrunner-server/endure@v1.4.5/pkg/container/serve.go:18 +0x198
github.com/roadrunner-server/endure/pkg/container.(*Endure).serveInternal(0x140007fc380, 0x1400000c528)
	github.com/roadrunner-server/endure@v1.4.5/pkg/container/serve.go:50 +0x1a8
github.com/roadrunner-server/endure/pkg/container.(*Endure).Start(0x140007fc380)
	github.com/roadrunner-server/endure@v1.4.5/pkg/container/endure.go:445 +0x78
reflect.Value.call({0x14000200900?, 0x14000206e88?, 0x108460108?}, {0x1063d91be, 0x4}, {0x1400000c9d8, 0x1, 0x105370848?})
	reflect/value.go:584 +0x688
reflect.Value.Call({0x14000200900?, 0x14000206e88?, 0x14000000001?}, {0x1400000c9d8?, 0x14000abf998?, 0x104f9038c?})
	reflect/value.go:368 +0x90
github.com/roadrunner-server/endure/pkg/fsm.(*FSMImpl).Transition(0x14000199c08, 0x1, {0x14000205b00, 0x1, 0x140007fc380?})
	github.com/roadrunner-server/endure@v1.4.5/pkg/fsm/fsm.go:198 +0x618
github.com/roadrunner-server/endure/pkg/container.(*Endure).Serve(0x140007fc380)
	github.com/roadrunner-server/endure@v1.4.5/pkg/container/endure.go:327 +0xcc
github.com/roadrunner-server/roadrunner/v2/internal/cli/serve.NewCommand.func1(0x14000940a00, {0x1063d977a, 0x0, 0x0})
	github.com/roadrunner-server/roadrunner/v2/internal/cli/serve/command.go:66 +0x3d4
github.com/spf13/cobra.(*Command).execute(0x14000940a00, {0x107b06178, 0x0, 0x0})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000940280)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.run()
	github.com/roadrunner-server/roadrunner/v2/cmd/rr/main.go:21 +0x44
main.main()
	github.com/roadrunner-server/roadrunner/v2/cmd/rr/main.go:15 +0x1c
```

**Comment by rustatian** [comment]
fixed by: https://github.com/temporalio/roadrunner-temporal/commit/c72aab8f38d7920968a2942f06cd7ab1519d918e
