### ISSUE TITLE
[🐛 BUG]: Panic in grpc plugin

### ISSUE THREAD

**Issue by genhoi** [roadrunner-server/roadrunner#1532]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Sometimes RR doesn't start and ends with an error with exit code: 1

### Version (rr --version)

2023.1.0-rc.2

### How to reproduce the issue?

I don't have a clear idea how to reproduce the bug since it doesn't always appear

### Relevant log output

```shell
2023-04-10T13:17:01+0000	DEBUG	server      	worker is allocated	{"pid": 17, "internal_event_name": "EventWorkerConstruct"}
2023-04-10T13:17:01+0000	DEBUG	server      	worker is allocated	{"pid": 13, "internal_event_name": "EventWorkerConstruct"}
2023-04-10T13:17:01+0000	INFO	grpc        	grpc server was started	{"address": "tcp://0.0.0.0:22164"}
handle_serve_command: Function call error:
	got initial serve error from the Vertex *metrics.Plugin, stopping execution, error: duplicate metrics collector registration attempted
2023-04-10T13:18:11+0000	DEBUG	server      	worker is allocated	{"pid": 15, "internal_event_name": "EventWorkerConstruct"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdb9641]

goroutine 97 [running]:
github.com/roadrunner-server/grpc/v4.(*Plugin).Workers(0xc000c44080?)
	github.com/roadrunner-server/grpc/v4@v4.1.6/plugin.go:222 +0xc1
github.com/roadrunner-server/sdk/v4/metrics.(*StatsExporter).Collect(0xc0000a7180, 0xc00059a760?)
	github.com/roadrunner-server/sdk/v4@v4.2.0/metrics/metrics.go:42 +0x4a
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:456 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:548 +0xc09
```

**Comment by rustatian** [comment]
Hey @genhoi 👋🏻 

Do you use metrics? Could you please share your configuration as well?

**Comment by genhoi** [comment]
@rustatian Hi, yes, we use metrics )

```
version: "3"

server:
  command: "php /app/public/index.php"
  env:
    - APP_RUNTIME: 'Baldinof\RoadRunnerBundle\Runtime\Runtime'
    - RR_MODE: 'grpc'

rpc:
  listen: ${RR_RPC}

metrics:
  address: "0.0.0.0:${RR_METRICS_PORT}"

grpc:
  listen: "tcp://0.0.0.0:${RR_GRPC_PORT}"
  proto:
    - "/app/proto/services.proto"
  pool:
    num_workers: ${RR_GRPC_WORKERS_COUNT}
    debug: ${RR_GRPC_WORKERS_DEBUG}

service:
  update-automatic-collection-items:
    command: "php /app/bin/console app:update-automatic-collection-items"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 900
  update-section-items:
    command: "php /app/bin/console app:update-section-items"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1800
  update-collection-sections:
    command: "php /app/bin/console app:update-collection-sections"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 7200
  update-is-draft-items:
    command: "php /app/bin/console app:update-is-draft-items"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 7200
  sync-collection-item-consume:
    command: "php /app/bin/console messenger:consume sync-collection-item-consume"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 30
  sync-item-size-data-consume:
    command: "php /app/bin/console messenger:consume sync-item-size-data-consume"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 30
  fill-indexing-filters:
    command: "php /app/bin/console app:fill-indexing-filters"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1200
  messenger-setup-transports:
    command: "php /app/bin/console messenger:setup-transports"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 30
  collect-metrics:
    command: "php /app/bin/console app:collect-metrics"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 3600
  collect-item-metrics:
    command: "php /app/bin/console app:collect-item-metrics"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1800
  sync-category-item-attribute-values:
    command: "php /app/bin/console app:sync-category-item-attribute-values"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 60
```

**Comment by rustatian** [comment]
@genhoi Thanks 👍🏻 . I understand the reason for panic, but if you're using metrics, you should avoid duplicate metric registrations. Prometheus does not allow this.
You may try the new [lock](https://github.com/roadrunner-php/lock) plugin to register metrics only once.

**Comment by genhoi** [comment]
@rustatian 👍🏻
Thank you, we will add the use of locks
