### ISSUE TITLE
[🐛 BUG]: Can't pass priority value for pipeline for Jobs plugin with JSON config file

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1557]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

### Version (rr --version)

rr version 2.12.3 (build time: 2023-02-16T13:08:41+0000, go1.20), OS: linux, arch: amd64
and
rr version 2023.1.2 (build time: 2023-05-04T13:19:13+0000, go1.20.4), OS: linux, arch: amd64

### How to reproduce the issue?

Run `rr serve -c rr.json` with following rr.json:

```json
{
    "version": "2.7",
    "rpc": {
        "listen": "tcp:\/\/127.0.0.1:6001"
    },
    "metrics": {
        "address": "0.0.0.0:9254"
    },
    "server": {
        "command": "\/usr\/local\/bin\/php public\/worker.php"
    },
    "amqp": {
        "addr": "amqp:\/\/guest:guest@rabbitmq:5672"
    },
    "jobs": {
        "num_pollers": 1,
        "pool": {
            "num_workers": 1,
            "max_jobs": 1
        },
        "consume": [
            "test"
        ],
        "pipelines": {
            "test": {
                "driver": "amqp",
                "config": {
                    "queue": "test",
                    "priority": 10
                }
            }
        }
    }
}
```

Without `priority` all works fine.

### Relevant log output

```shell
panic: interface conversion: interface {} is float64, not int

goroutine 1 [running]:
github.com/roadrunner-server/sdk/v3/plugins/jobs/pipeline.(*Pipeline).Int(...)
        github.com/roadrunner-server/sdk/v3@v3.2.0/plugins/jobs/pipeline/pipeline.go:94
github.com/roadrunner-server/jobs/v3.(*Config).InitDefaults(0xc000a2a4c0)
        github.com/roadrunner-server/jobs/v3@v3.2.0/config.go:56 +0x3d9
github.com/roadrunner-server/jobs/v3.(*Plugin).Init(0xc0001fe1e0, {0x7fb078fae978, 0xc00059ad00}, 0xc000967650, {0x7fb078fae9a0?, 0xc00059ad80})
        github.com/roadrunner-server/jobs/v3@v3.2.0/plugin.go:83 +0xda
reflect.Value.call({0xc0004eaf00?, 0xc0004f0d78?, 0x0?}, {0x1b6366a, 0x4}, {0xc000a0f800, 0x4, 0x0?})
        reflect/value.go:586 +0xb07
reflect.Value.Call({0xc0004eaf00?, 0xc0004f0d78?, 0x177019c?}, {0xc000a0f800?, 0x1e05c00?, 0x190d240?})
        reflect/value.go:370 +0xbc
github.com/roadrunner-server/endure/pkg/container.(*Endure).callInitFn(0xc000135a00, {{0x1754df4, 0x4}, {0x0, 0x0}, {0x1e05c00, 0xc0004eaf00}, {0xc0004eaf00, 0xc0004f0d78, 0x13}, 
...}, ...)
        github.com/roadrunner-server/endure@v1.4.6/pkg/container/init.go:54 +0x165
github.com/roadrunner-server/endure/pkg/container.(*Endure).internalInit(0xc000135a00, 0xc0009e5a20)
        github.com/roadrunner-server/endure@v1.4.6/pkg/container/init.go:25 +0x108
github.com/roadrunner-server/endure/pkg/container.(*Endure).Initialize(0xc000135a00)
        github.com/roadrunner-server/endure@v1.4.6/pkg/container/endure.go:404 +0x916
reflect.Value.call({0xc0005e8e10?, 0xc000012ad0?, 0x7fb0a06a0108?}, {0x1b6366a, 0x4}, {0xc000011068, 0x1, 0x0?})
        reflect/value.go:586 +0xb07
reflect.Value.Call({0xc0005e8e10?, 0xc000012ad0?, 0x0?}, {0xc000011068?, 0x2a6de80?, 0xc00085f990?})
        reflect/value.go:370 +0xbc
github.com/roadrunner-server/endure/pkg/fsm.(*FSMImpl).Transition(0xc000010eb8, 0x0, {0xc000746cd0, 0x1, 0x1a85e20?})
        github.com/roadrunner-server/endure@v1.4.6/pkg/fsm/fsm.go:180 +0x4f7
github.com/roadrunner-server/endure/pkg/container.(*Endure).Init(0xc000135a00)
        github.com/roadrunner-server/endure@v1.4.6/pkg/container/endure.go:314 +0xca
github.com/roadrunner-server/roadrunner/v2/internal/cli/serve.NewCommand.func1(0xc000742900, {0x1b63bc6, 0x2, 0x2})
        github.com/roadrunner-server/roadrunner/v2/internal/cli/serve/command.go:60 +0x395
github.com/spf13/cobra.(*Command).execute(0xc000742900, {0xc0004c0d60, 0x2, 0x2})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000742000)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x7ffda88c4cbd?)
        github.com/spf13/cobra@v1.6.1/command.go:968 +0x19
main.run()
        github.com/roadrunner-server/roadrunner/v2/cmd/rr/main.go:26 +0x45
main.main()
        github.com/roadrunner-server/roadrunner/v2/cmd/rr/main.go:16 +0x19
```

**Comment by rustatian** [comment]
Hey @embargo2710 👋🏻 
Oh yeah, good old JSON 😄

**Comment by rustatian** [comment]
Done, will be released today as a bugfix release, thanks for the contribution 👍🏻
