### ISSUE TITLE
[🐛 BUG]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1597]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

### Version (rr --version)

version: 2023.1.4, buildtime: 2023-05-25T11:10:33+0000

### How to reproduce the issue?

Just run the RR!

### Relevant log output

```shell
июн 08 13:07:43 server-01 rr[20656]: [INFO] RoadRunner server started; version: 2023.1.4, buildtime: 2023-05-25T11:10:33+0000
июн 08 13:08:17 server-01 rr[20656]: panic: runtime error: invalid memory address or nil pointer dereference
июн 08 13:08:17 server-01 rr[20656]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc648b4]
июн 08 13:08:17 server-01 rr[20656]: goroutine 758 [running]:
июн 08 13:08:17 server-01 rr[20656]: github.com/roadrunner-server/sdk/v4/pool/static_pool.(*Pool).Workers(0x416190?)
июн 08 13:08:17 server-01 rr[20656]:         github.com/roadrunner-server/sdk/v4@v4.2.6/pool/static_pool/static_pool.go:119 +0x14
июн 08 13:08:17 server-01 rr[20656]: github.com/roadrunner-server/jobs/v4.(*Plugin).Workers(0xc00005cb00)
июн 08 13:08:17 server-01 rr[20656]:         github.com/roadrunner-server/jobs/v4@v4.3.10/plugin.go:275 +0x67
июн 08 13:08:17 server-01 rr[20656]: github.com/roadrunner-server/sdk/v4/metrics.(*StatsExporter).Collect(0xc000ae4140, 0xc0007e56e0?)
```

**Comment by rustatian** [comment]
Closed as resolved.
