### ISSUE TITLE
[🐛 BUG]: `./vendor/bin/rr get-binary` fails on FreeBSD 14 amd64

### ISSUE THREAD

**Issue by slegrand45** [roadrunner-server/roadrunner#2007]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello,

I tried the Composer method to install RoadRunner on a FreeBSD 14 system and the command `./vendor/bin/rr get-binary` fails.

### Version (rr --version)

Not applicable as this is a problem with installation.

### How to reproduce the issue?

On a FreeBSD 14 system:
```
composer require spiral/roadrunner-cli
./vendor/bin/rr get-binary
```

### Relevant log output

```shell
Fatal error: Uncaught OutOfRangeException: Current architecture (amd64) may not be supported in /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php:60
Stack trace:
#0 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Environment/Architecture.php(37): Spiral\RoadRunner\Console\Environment\Architecture\Factory->createFromGlobals()
#1 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Command/ArchitectureOption.php(44): Spiral\RoadRunner\Console\Environment\Architecture::createFromGlobals()
#2 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Command/Option.php(56): Spiral\RoadRunner\Console\Command\ArchitectureOption->default()
#3 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Command/Option.php(38): Spiral\RoadRunner\Console\Command\Option->register(Object(Spiral\RoadRunner\Console\GetBinaryCommand), 'arch', 'a')
#4 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Command/ArchitectureOption.php(28): Spiral\RoadRunner\Console\Command\Option->__construct(Object(Spiral\RoadRunner\Console\GetBinaryCommand), 'arch', 'a')
#5 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/GetBinaryCommand.php(75): Spiral\RoadRunner\Console\Command\ArchitectureOption->__construct(Object(Spiral\RoadRunner\Console\GetBinaryCommand))
#6 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/bin/rr(71): Spiral\RoadRunner\Console\GetBinaryCommand->__construct()
#7 /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/bin/rr(119): include('/home/stephane/...')
#8 {main}
  thrown in /home/stephane/TMP/php/roadrunner/test-get-binary/vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php on line 60
```

**Comment by rustatian** [comment]
Hey @slegrand45 👋 
Thanks for the report 👍 
`./vendor/bin/rr get-binary` is not a part of RR. It's a PHP helper library.
Could you please move this issue to the https://github.com/roadrunner-php/issues repository to be notified about its progress? (Because if I recreate this issue in the `roadrunner-php` repo, you won't get notified).

**Comment by slegrand45** [comment]
Hi,

Move to https://github.com/roadrunner-php/issues/issues/37
